# Generated by Django 5.2 on 2025-05-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-show_time']},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theater.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
